/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../web/src/app${'/(auth)'}/forgot-password/page` | `/../../web/src/app/forgot-password/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/src/app${'/(auth)'}/reset-password/page` | `/../../web/src/app/reset-password/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/record` | `/record`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recordings` | `/recordings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/post-call/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/recording/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../../web/src/app${'/(auth)'}/forgot-password/page` | `/../../web/src/app/forgot-password/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/src/app${'/(auth)'}/reset-password/page` | `/../../web/src/app/reset-password/page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/record` | `/record`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recordings` | `/recordings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/post-call/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/recording/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../../web/src/app${'/(auth)'}/forgot-password/page${`?${string}` | `#${string}` | ''}` | `/../../web/src/app/forgot-password/page${`?${string}` | `#${string}` | ''}` | `/../../web/src/app${'/(auth)'}/reset-password/page${`?${string}` | `#${string}` | ''}` | `/../../web/src/app/reset-password/page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/record${`?${string}` | `#${string}` | ''}` | `/record${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recordings${`?${string}` | `#${string}` | ''}` | `/recordings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../web/src/app${'/(auth)'}/forgot-password/page` | `/../../web/src/app/forgot-password/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/src/app${'/(auth)'}/reset-password/page` | `/../../web/src/app/reset-password/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/record` | `/record`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recordings` | `/recordings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/post-call/${Router.SingleRoutePart<T>}` | `/recording/${Router.SingleRoutePart<T>}` | { pathname: `/post-call/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/recording/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
